name: main
on: [push]

jobs:
  pages-directory-listing-master:
    runs-on: ubuntu-latest
    name: Run Actions Template
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dummy-data

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@main
        with:
          FOLDER: data

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: data
